### ISSUE TITLE
Some files don't have right extension

### ISSUE THREAD

**Issue by jai-dewani** [utkarsh-raj/snippets#11] opened 2018-10-30 11:27 UTC
- [Codechef_BINIM2](https://github.com/utkarsh-raj/snippets/blob/master/codechef_BINIM2)
- [codechef_RECTANGL](https://github.com/utkarsh-raj/snippets/blob/master/codechef_RECTANGL)
- [codeshef_ADASTAIR](https://github.com/utkarsh-raj/snippets/blob/master/codeshef_ADASTAIR)

**Comment by utkarsh-raj** [comment] 2018-11-24 10:33
If the issue is still open, should you be assigned to it @jai-dewani ?

**Comment by jai-dewani** [comment] 2018-11-28 15:29
The issue has been addressed in #14  
- [x] Successfully merged into master branch

**Comment by jai-dewani** [comment] 2018-11-28 15:30
Next set of files which require correct extensions:
- [ ] [Codechef_EID](https://github.com/utkarsh-raj/snippets/blob/master/codechef_EID)
- [ ] [Codechef_PROBSET](https://github.com/utkarsh-raj/snippets/blob/master/codechef_PROBSET)
- [ ] [codechef_START01](https://github.com/utkarsh-raj/snippets/blob/master/codechef_START01)

**Comment by utkarsh-raj** [comment] 2019-10-10 14:45
Can you please raise a new issue so that new volunteers can be try the fixes @jai-dewani ?

**Closed as completed** 2019-10-10 14:47 UTC
Labels: good first issue
